site_name: "Solicen • Docs"
repo_url: https://github.com/SolicenTEAM/opendocs
repo_name: SolicenTEAM/opendocs
edit_uri: edit/main/docs/

extra_css: [extra.css]
theme:
  name: material
  palette:
      scheme: slate
      primary: black
  features:
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.expand
    - navigation.prune
    - navigation.instant.progress
    - header.autohide
    - toc.follow
    - search.suggest
    - search.share
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.tooltips
    - content.code.copy
    - content.code.select
    - content.action.edit
    - content.action.view
  language: ru
  markdown_extensions:
  - footnotes
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  plugins:
    - search
    - table-reader
    - glightbox
    - social
  extra:
    status:
      new: Недавно добавлено
      deprecated: Устарело

nav:
  - Добро пожаловать: index.md
  - ГАЙДЫ:
    - Unreal Engine: guides/unreal engine.md

    - Устарело:
      - Основа системы Солицена:
        - Solicen Universal Installer:
          - Что за SUI?: Solicen/SUI/WhatIsSUI.md
          - Функционал установщика: Solicen/SUI/Functional.md
        - Solicen Open Format:
          - Открытый формат: Solicen/SOFFormat.md
          - Работа с строками: Solicen/strings.md
      - Создание переводов:
        - KiriKiri Engine (.xp3): 
          - Перевод игр созданных на KiriKiri Engine: Translation/kirikiri.md
        - Ren'Py Visual Novel:
          - Перевод игр созданных на Ren'Py Engine: Translation/renpy.md
        - Unreal Engine:
          - Перевод игр созданных на Unreal Engine: Translation/unrealengine.md   
  
 # - Работа с портами:
 #   - Как делают порты?: SolicenTEAM/howToMakePorts.md
 # - Создание модов:
 #     - DDLC: 
 #       - Как создают моды?: SolicenTEAM/DDLC/makeMods.md
 #     - Barotrauma:
 #       - Как создают моды?: SolicenTEAM/Barotrauma/makeMods.md